version: '3.1'
services:
  mongo:
    image: mongo
    command: --smallfiles
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
  backend:
    build: 
      context: ./express-file-upload
      dockerfile: Dockerfile
    environment:
      NODE_ENV: development
    ports:
      - 3000:3000 
  frontend:
    build: 
      context: ./app-image-upload-frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"    