version: '3.1'
services:
  mongo-db:
    image: mongo
    command: --smallfiles
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    restart: always
    ports:
      - 27017:27017